name: Change Issue Label on PR Merge (GraphQL)

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  update-label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    
    steps:
      - name: Fetch Linked Issues via GraphQL
        id: get_linked_issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # 1. Create the GraphQL query and variables JSON
          cat <<EOF > graphql-query.json
          {
            "query": "query(\$owner: String!, \$repo: String!, \$pr: Int!) { repository(owner: \$owner, name: \$repo) { pullRequest(number: \$pr) { closingIssuesReferences(first: 100) { nodes { number } } } } }",
            "variables": {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "pr": ${{ github.event.pull_request.number }}
            }
          }
          EOF
          
          # 2. Execute the query using the JSON payload
          ISSUE_NUMBERS=$(gh api graphql --input graphql-query.json --jq '.data.repository.pullRequest.closingIssuesReferences.nodes[].number' | tr '\n' ' ')
          
          echo "Found linked issue numbers: $ISSUE_NUMBERS"
          echo "issue_numbers=$ISSUE_NUMBERS" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update Labels for Each Linked Issue
        if: steps.get_linked_issues.outputs.issue_numbers != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLD_LABEL: "status: in progress"
          NEW_LABEL: "status: in dev"
        run: |
          for ISSUE_NUMBER in ${{ steps.get_linked_issues.outputs.issue_numbers }}; do
            echo "Processing issue #$ISSUE_NUMBER"
            gh issue edit $ISSUE_NUMBER --repo ${{ github.repository }} --remove-label "$OLD_LABEL"
            gh issue edit $ISSUE_NUMBER --repo ${{ github.repository }} --add-label "$NEW_LABEL"
          done
        shell: bash
