name: test-pandoc

on:
  workflow_dispatch:

jobs:

  minimal-pandoc:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-pandoc@v2
    - run: echo "# Test" | pandoc -t html
